"""Tests for the PR body contract alignment layer (prd skill publish mode).

覆盖 :mod:`agent_runner_pr_body_contract` 的三段能力：skill 发布契约参考的
加载与 prompt 教学、发布端软门（锚点校验 + 不合规标注）、以及合并队列硬门
消费的 marker 解析。"""

from __future__ import annotations

from pathlib import Path

import pytest

from backend.core.use_cases.agent_runner_pr_body_contract import (
    MERGE_ACCEPTANCE_MARKER_TEXT,
    build_contract_annotation_block,
    build_contract_prompt_prefix,
    find_pr_body_contract_violations,
    has_contract_annotation,
    load_prd_publish_contract,
    parse_contract_annotation,
)

_ISSUE_BODY_WITH_PRD = "PRD path: `tasks/pending/20260928-feature.md`\n\nSome description."
_ISSUE_BODY_WITHOUT_PRD = "Just a bug report with no PRD anchor."
_COMPLIANT_BODY = "\n".join(
    [
        "Closes #42",
        "",
        "- PRD: tasks/pending/20260928-feature.md",
        "Merging this PR constitutes acceptance and authorizes archival.",
        MERGE_ACCEPTANCE_MARKER_TEXT,
        "",
    ]
)


def _write_skill(tmp_path: Path, *, with_reference: bool) -> Path:
    """在 tmp_path 下伪造一份最小 prd skill 安装，返回 SKILL.md 路径。"""
    skill_dir = tmp_path / "skills" / "prd"
    skill_dir.mkdir(parents=True)
    skill_path = skill_dir / "SKILL.md"
    skill_path.write_text("---\nname: prd\n---\n# PRD Generator\n", encoding="utf-8")
    if with_reference:
        references_dir = skill_dir / "references"
        references_dir.mkdir()
        (references_dir / "pr-evidence-and-merge-acceptance.md").write_text(
            "# PR Evidence And Merge Acceptance\n1. The PR body uniquely names the PRD.\n",
            encoding="utf-8",
        )
    return skill_path


def test_load_prd_publish_contract_reads_reference(tmp_path: Path) -> None:
    """契约参考文本应从 SKILL.md 同级 references/ 目录读取。"""
    skill_path = _write_skill(tmp_path, with_reference=True)
    contract_text = load_prd_publish_contract(skill_path)
    assert contract_text is not None
    assert "PR-Native" in contract_text or "PR body" in contract_text


def test_load_prd_publish_contract_returns_none_without_reference(tmp_path: Path) -> None:
    """skill 存在但参考文档缺失（旧版安装）时应安全返回 None。"""
    skill_path = _write_skill(tmp_path, with_reference=False)
    assert load_prd_publish_contract(skill_path) is None


def test_load_prd_publish_contract_returns_none_when_skill_missing(tmp_path: Path) -> None:
    """skill 完全不可达时应安全返回 None 而不是抛错。"""
    assert load_prd_publish_contract(tmp_path / "nonexistent" / "SKILL.md") is None


def test_contract_prompt_prefix_contains_teaching_anchors(tmp_path: Path) -> None:
    """prompt 教学段必须包含 PRD 行、merge-acceptance marker 与参考文本。"""
    skill_path = _write_skill(tmp_path, with_reference=True)
    contract_text = load_prd_publish_contract(skill_path)
    assert contract_text is not None
    prefix = build_contract_prompt_prefix(contract_text)
    assert "- PRD: <relative prd path>" in prefix
    assert MERGE_ACCEPTANCE_MARKER_TEXT in prefix
    assert "Never pre-tick" in prefix
    assert "pr-evidence-and-merge-acceptance" in prefix or "PR body" in contract_text


def test_find_violations_flags_both_missing_anchors() -> None:
    """fallback body（只有 Closes）对 PRD 交付应同时缺 prd-link 与声明。"""
    violations = find_pr_body_contract_violations(
        "Closes #42\n\nGenerated by issue-agent-runner.\n", _ISSUE_BODY_WITH_PRD
    )
    assert violations == ["prd-link", "merge-acceptance"]


def test_find_violations_empty_for_compliant_body() -> None:
    assert find_pr_body_contract_violations(_COMPLIANT_BODY, _ISSUE_BODY_WITH_PRD) == []


def test_find_violations_skip_issues_without_prd() -> None:
    """无 PRD 锚点的 Issue 不新增契约要求（prd skill 管辖范围之外）。"""
    assert find_pr_body_contract_violations("Closes #7", _ISSUE_BODY_WITHOUT_PRD) == []


def test_annotation_block_roundtrip() -> None:
    """标注块写入的 marker 必须能被合并队列侧的解析函数原样读回。"""
    violations = ["prd-link", "merge-acceptance"]
    block = build_contract_annotation_block(violations)
    assert parse_contract_annotation(block) == violations
    assert has_contract_annotation(block) is True
    assert has_contract_annotation(_COMPLIANT_BODY) is False
    assert parse_contract_annotation(_COMPLIANT_BODY) == []


def test_annotation_block_lists_human_readable_descriptions() -> None:
    block = build_contract_annotation_block(["prd-link"])
    assert "`prd-link`" in block
    assert "pending PRD path" in block


@pytest.mark.parametrize(
    ("marker_line", "expected"),
    [
        ("<!-- iar:pr-contract version=1 missing=prd-link -->", ["prd-link"]),
        (
            "<!--iar:pr-contract version=1 missing=prd-link,merge-acceptance-->",
            ["prd-link", "merge-acceptance"],
        ),
        ("<!-- iar:pr-contract version=1 missing= -->", []),
    ],
)
def test_parse_contract_annotation_marker_variants(marker_line: str, expected: list[str]) -> None:
    assert parse_contract_annotation(marker_line) == expected


# ---------------------------------------------------------------------------
# 发布端软门集成：create_draft_pr 在 fallback body 上追加标注
# ---------------------------------------------------------------------------


def _publish_issue(number: int, body: str):
    from backend.core.shared.models.agent_runner import IssueSummary

    return IssueSummary(
        number=number,
        title="Test Feature",
        url=f"https://github.com/example/repo/issues/{number}",
        body=body,
        labels=(),
    )


def _fake_runner_for(branch: str):
    from backend.core.shared.models.agent_runner import CommandResult
    from tests.conftest import FakeProcessRunner
    from tests.support.agent_runner import git_remote_command, git_remote_result

    return FakeProcessRunner(
        responses={
            ("git", "branch", "--show-current"): CommandResult(
                command=("git", "branch", "--show-current"),
                return_code=0,
                stdout=f"{branch}\n",
                stderr="",
            ),
            ("git", "status", "--porcelain"): CommandResult(
                command=("git", "status", "--porcelain"),
                return_code=0,
                stdout="",
                stderr="",
            ),
            git_remote_command(): git_remote_result("origin"),
        }
    )


def test_create_draft_pr_appends_contract_annotation_for_fallback_body() -> None:
    """生成被禁用时 fallback body 对 PRD 交付必须被标注为契约不合规。"""
    from pathlib import Path

    from backend.core.shared.models.agent_runner import AppConfig
    from backend.core.use_cases.agent_runner_publish import create_draft_pr
    from tests.conftest import FakeGitHubClient

    issue = _publish_issue(42, _ISSUE_BODY_WITH_PRD)
    fake_client = FakeGitHubClient()
    branch, pr_url = create_draft_pr(
        issue,
        Path("."),
        AppConfig(),
        fake_client,
        _fake_runner_for("issue-42"),
    )
    assert pr_url
    pr_calls = [c for c in fake_client.calls if c["method"] == "create_draft_pr"]
    assert len(pr_calls) == 1
    body = pr_calls[0]["body"]
    assert body.startswith("Closes #42")
    assert has_contract_annotation(body)
    assert parse_contract_annotation(body) == ["prd-link", "merge-acceptance"]
    assert "autopilot merge queue will refuse" in body


def test_create_draft_pr_no_annotation_for_issues_without_prd() -> None:
    """无 PRD 锚点的 Issue 不追加契约标注。"""
    from pathlib import Path

    from backend.core.shared.models.agent_runner import AppConfig
    from backend.core.use_cases.agent_runner_publish import create_draft_pr
    from tests.conftest import FakeGitHubClient

    issue = _publish_issue(7, _ISSUE_BODY_WITHOUT_PRD)
    fake_client = FakeGitHubClient()
    create_draft_pr(issue, Path("."), AppConfig(), fake_client, _fake_runner_for("issue-7"))
    pr_calls = [c for c in fake_client.calls if c["method"] == "create_draft_pr"]
    assert has_contract_annotation(pr_calls[0]["body"]) is False


def test_create_draft_pr_injects_contract_teaching_into_agent_prompt(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    """agent 模式下发布契约参考文本必须进入生成 prompt（教学注入）。"""
    from backend.core.shared.models.agent_runner import (
        AppConfig,
        CommandResult,
        GeneratedContentConfig,
        GeneratedContentTargetConfig,
    )
    from backend.core.use_cases import agent_runner_publish as publish_module
    from backend.core.use_cases.agent_runner_publish import create_draft_pr
    from tests.conftest import FakeGitHubClient

    skill_path = _write_skill(tmp_path, with_reference=True)
    contract_text = load_prd_publish_contract(skill_path)
    assert contract_text is not None
    monkeypatch.setattr(publish_module, "load_prd_publish_contract", lambda: contract_text)

    captured_prompts: list[str] = []

    class RecordingGenerator:
        def generate(self, agent_name: str, prompt: str, *, cwd, timeout=None):
            captured_prompts.append(prompt)
            return CommandResult(
                command=("fake",),
                return_code=0,
                stdout=(
                    "[Agent] Test Feature\n\nCloses #42\n\n"
                    "- PRD: tasks/pending/20260928-feature.md\n"
                    f"{MERGE_ACCEPTANCE_MARKER_TEXT}\n"
                ),
                stderr="",
            )

    app_config = AppConfig(
        generated_content=GeneratedContentConfig(
            enabled=True,
            draft_pr=GeneratedContentTargetConfig(
                enabled=True,
                mode="agent",
                output="markdown",
                prompt="Generate a draft PR body.",
            ),
        ),
    )
    issue = _publish_issue(42, _ISSUE_BODY_WITH_PRD)
    fake_client = FakeGitHubClient()
    create_draft_pr(
        issue,
        Path("."),
        app_config,
        fake_client,
        _fake_runner_for("issue-42"),
        content_generator=RecordingGenerator(),
    )
    assert captured_prompts, "agent generator should have been invoked"
    assert "PR-Native Acceptance contract" in captured_prompts[0]
    assert MERGE_ACCEPTANCE_MARKER_TEXT in captured_prompts[0]
    # 教学注入后原 config prompt 仍保留在 prompt 尾部。
    assert captured_prompts[0].endswith("Generate a draft PR body.")
    # 合规正文不应被追加标注块。
    pr_calls = [c for c in fake_client.calls if c["method"] == "create_draft_pr"]
    assert has_contract_annotation(pr_calls[0]["body"]) is False


# ---------------------------------------------------------------------------
# 合并端硬门集成：带标注 marker 的 PR 不自动合并
# ---------------------------------------------------------------------------


def test_merge_queue_skips_prs_with_contract_annotation(tmp_path) -> None:
    """发布端标注过 ``iar:pr-contract`` 的 PR 必须被合并队列拒绝。"""
    from backend.core.shared.models.agent_runner import PullRequestContext
    from backend.core.use_cases.agent_runner_merge_queue import _process_one
    from tests.conftest import FakeGitHubClient, FakeProcessRunner
    from tests.test_agent_runner_merge_queue import _make_config, _make_issue

    github = FakeGitHubClient()
    pr_context = PullRequestContext(
        pr_url="https://github.com/example/repo/pull/70",
        branch="issue-70",
        head_sha="abc1234",
        base_sha="base1234",
        mergeable=True,
        checks_state="SUCCESS",
        number=70,
        body="Closes #70\n\n" + build_contract_annotation_block(["prd-link"]),
    )
    github.set_pr_context("issue-70", pr_context)
    github._issue_comments[70] = ["PR Branch: `issue-70`"]

    outcome = _process_one(
        repo_path=tmp_path,
        config=_make_config(require_verifier_pass=False, auto_sign_off=False),
        issue=_make_issue(number=70, labels=("agent/review",)),
        github_client=github,
        process_runner=FakeProcessRunner(),
        supervisor_agent="auto",
    )
    assert outcome.action == "skipped_pr_contract_missing"
    merge_calls = [c for c in github.calls if c.get("method") == "merge_pull_request"]
    assert merge_calls == []
    # 硬门在 rebase / 签核之前生效，不产生 body 变更。
    body_calls = [c for c in github.calls if c.get("method") == "update_pull_request_body"]
    assert body_calls == []


def test_merge_queue_merges_prs_without_contract_annotation(tmp_path, monkeypatch) -> None:
    """无标注 marker 的 PR（含存量 PR）不受硬门影响。"""
    from backend.core.shared.models.agent_runner import (
        CommandResult,
        PullRequestContext,
    )
    from backend.core.use_cases.agent_runner_merge_queue import _process_one
    from tests.conftest import FakeGitHubClient, FakeProcessRunner
    from tests.test_agent_runner_merge_queue import _make_config, _make_issue

    # 复用 merge queue 测试模块的 worktree stub：_process_one 会解析 worktree。
    stub_worktree = tmp_path / "worktree"
    stub_worktree.mkdir()
    monkeypatch.setattr(
        "backend.core.use_cases.agent_runner_merge_queue.create_or_reuse_worktree",
        lambda *args, **kwargs: stub_worktree,
    )

    def fake_run_verification(*args, **kwargs):  # noqa: ARG001,ANN002,ANN003
        return [CommandResult(command=("git", "status"), return_code=0, stdout="", stderr="")]

    monkeypatch.setattr(
        "backend.core.use_cases.agent_runner_merge_queue.run_verification",
        fake_run_verification,
    )
    monkeypatch.setattr(
        "backend.core.use_cases.agent_runner_merge_queue.execute_rebase",
        lambda **kwargs: [],
    )
    monkeypatch.setattr(
        "backend.core.use_cases.agent_runner_merge_queue._diff_paths",
        lambda *args, **kwargs: (["src/main.py"], False),
    )

    github = FakeGitHubClient()
    pr_context = PullRequestContext(
        pr_url="https://github.com/example/repo/pull/71",
        branch="issue-71",
        head_sha="abc1234",
        base_sha="base1234",
        mergeable=True,
        checks_state="SUCCESS",
        number=71,
        body="Closes #71\n\nGenerated by issue-agent-runner.\n",
    )
    github.set_pr_context("issue-71", pr_context)
    github._issue_comments[71] = ["PR Branch: `issue-71`"]

    outcome = _process_one(
        repo_path=tmp_path,
        config=_make_config(require_verifier_pass=False, auto_sign_off=False),
        issue=_make_issue(number=71, labels=("agent/review",)),
        github_client=github,
        process_runner=FakeProcessRunner(),
        supervisor_agent="auto",
    )
    assert outcome.action == "merged"
