"""Tests for the PR body contract alignment layer (prd skill publish mode).

覆盖 :mod:`agent_runner_pr_body_contract` 的四段能力：skill 发布契约参考的
加载与 prompt 教学、确定性正文补锚点、发布端软门（锚点校验 + 不合规标注）、
以及合并队列硬门消费的 marker 解析。"""

from __future__ import annotations

from pathlib import Path

import pytest

from backend.core.use_cases.agent_runner_pr_body_contract import (
    MERGE_ACCEPTANCE_MARKER_TEXT,
    append_missing_contract_anchors,
    build_contract_annotation_block,
    build_contract_prompt_prefix,
    find_pr_body_contract_violations,
    has_contract_annotation,
    load_prd_publish_contract,
    parse_contract_annotation,
)

_ISSUE_BODY_WITH_PRD = "PRD path: `tasks/pending/20260928-feature.md`\n\nSome description."
_ISSUE_BODY_WITHOUT_PRD = "Just a bug report with no PRD anchor."
_PENDING_PRD_PATH = "tasks/pending/20260928-feature.md"
_ARCHIVED_PRD_PATH = "tasks/archive/20260928-feature.md"
_COMPLIANT_BODY = "\n".join(
    [
        "Closes #42",
        "",
        "- PRD: tasks/pending/20260928-feature.md",
        "Merging this PR authorizes post-merge acceptance recording on the linked PRD.",
        MERGE_ACCEPTANCE_MARKER_TEXT,
        "",
    ]
)


def _write_skill(tmp_path: Path, *, with_reference: bool) -> Path:
    """在 tmp_path 下伪造一份最小 prd skill 安装，返回 SKILL.md 路径。"""
    skill_dir = tmp_path / "skills" / "prd"
    skill_dir.mkdir(parents=True)
    skill_path = skill_dir / "SKILL.md"
    skill_path.write_text("---\nname: prd\n---\n# PRD Generator\n", encoding="utf-8")
    if with_reference:
        references_dir = skill_dir / "references"
        references_dir.mkdir()
        (references_dir / "pr-evidence-and-merge-acceptance.md").write_text(
            "# PR Evidence And Merge Acceptance\n1. The PR body uniquely names the PRD.\n",
            encoding="utf-8",
        )
    return skill_path


def test_load_prd_publish_contract_reads_reference(tmp_path: Path) -> None:
    """契约参考文本应从 SKILL.md 同级 references/ 目录读取。"""
    skill_path = _write_skill(tmp_path, with_reference=True)
    contract_text = load_prd_publish_contract(skill_path)
    assert contract_text is not None
    assert "PR-Native" in contract_text or "PR body" in contract_text


def test_load_prd_publish_contract_returns_none_without_reference(tmp_path: Path) -> None:
    """skill 存在但参考文档缺失（旧版安装）时应安全返回 None。"""
    skill_path = _write_skill(tmp_path, with_reference=False)
    assert load_prd_publish_contract(skill_path) is None


def test_load_prd_publish_contract_returns_none_when_skill_missing(tmp_path: Path) -> None:
    """skill 完全不可达时应安全返回 None 而不是抛错。"""
    assert load_prd_publish_contract(tmp_path / "nonexistent" / "SKILL.md") is None


def test_contract_prompt_prefix_contains_teaching_anchors(tmp_path: Path) -> None:
    """prompt 教学段必须包含 PRD 行、merge-acceptance marker 与参考文本。"""
    skill_path = _write_skill(tmp_path, with_reference=True)
    contract_text = load_prd_publish_contract(skill_path)
    assert contract_text is not None
    prefix = build_contract_prompt_prefix(contract_text)
    assert "- PRD: <relative prd path>" in prefix
    # rv-6：PRD 在本 PR 里归档，教学指向归档位置，合并授权的是事后补记验收。
    assert "`tasks/archive/` location" in prefix
    assert "authorizes post-merge acceptance recording" in prefix
    assert "post-merge archival" not in prefix
    assert MERGE_ACCEPTANCE_MARKER_TEXT in prefix
    assert "Never pre-tick" in prefix
    assert "pr-evidence-and-merge-acceptance" in prefix or "PR body" in contract_text


def test_find_violations_flags_both_missing_anchors() -> None:
    """fallback body（只有 Closes）对 PRD 交付应同时缺 prd-link 与声明。"""
    violations = find_pr_body_contract_violations(
        "Closes #42\n\nGenerated by issue-agent-runner.\n", _ISSUE_BODY_WITH_PRD
    )
    assert violations == ["prd-link", "merge-acceptance"]


def test_find_violations_empty_for_compliant_body() -> None:
    assert find_pr_body_contract_violations(_COMPLIANT_BODY, _ISSUE_BODY_WITH_PRD) == []


def test_find_violations_skip_issues_without_prd() -> None:
    """无 PRD 锚点的 Issue 不新增契约要求（prd skill 管辖范围之外）。"""
    assert find_pr_body_contract_violations("Closes #7", _ISSUE_BODY_WITHOUT_PRD) == []


@pytest.mark.parametrize(
    "linked_prd_path",
    (
        pytest.param(_ARCHIVED_PRD_PATH, id="archived-path"),
        pytest.param(_PENDING_PRD_PATH, id="pending-path"),
    ),
)
def test_find_violations_accepts_archived_or_pending_prd_path(linked_prd_path: str) -> None:
    """rv-6：PRD 在本 PR 里归档，正文写归档路径或 Issue 的 pending 路径都满足 prd-link。"""
    pr_body = f"Closes #42\n\n- PRD: {linked_prd_path}\n{MERGE_ACCEPTANCE_MARKER_TEXT}\n"
    assert find_pr_body_contract_violations(pr_body, _ISSUE_BODY_WITH_PRD) == []


def test_find_violations_flags_prd_link_when_neither_path_is_referenced() -> None:
    """rv-6：两种路径都没出现时仍报 prd-link（换了目录的同名文件也不算）。"""
    pr_body = f"Closes #42\n\n- PRD: tasks/20260928-feature.md\n{MERGE_ACCEPTANCE_MARKER_TEXT}\n"
    assert find_pr_body_contract_violations(pr_body, _ISSUE_BODY_WITH_PRD) == ["prd-link"]


def test_append_missing_contract_anchors_makes_fallback_body_compliant() -> None:
    """rv-6：fallback body 补齐后通过契约校验；PRD 行写归档路径，声明句授权事后补记验收。

    小节标题与 merge-acceptance marker 被合并队列消费方钉住，逐字不变。
    """
    fallback_body = "Closes #42\n\nGenerated by issue-agent-runner.\n"
    completed_body = append_missing_contract_anchors(fallback_body, _ISSUE_BODY_WITH_PRD)
    assert completed_body.startswith(fallback_body.rstrip())
    assert f"- PRD: {_ARCHIVED_PRD_PATH}" in completed_body
    assert _PENDING_PRD_PATH not in completed_body
    assert "## Human Acceptance And PRD Archive" in completed_body
    assert "<!-- iar:merge-acceptance version=1 -->" in completed_body
    assert MERGE_ACCEPTANCE_MARKER_TEXT == "<!-- iar:merge-acceptance version=1 -->"
    assert "authorizes post-merge acceptance recording" in completed_body
    assert "post-merge archival" not in completed_body
    assert find_pr_body_contract_violations(completed_body, _ISSUE_BODY_WITH_PRD) == []
    assert has_contract_annotation(completed_body) is False


def test_append_missing_contract_anchors_leaves_compliant_body_untouched() -> None:
    """锚点已齐全的正文原样返回；补齐结果再补一次也不变（幂等）。"""
    assert append_missing_contract_anchors(_COMPLIANT_BODY, _ISSUE_BODY_WITH_PRD) == _COMPLIANT_BODY
    completed_body = append_missing_contract_anchors("Closes #42\n", _ISSUE_BODY_WITH_PRD)
    assert append_missing_contract_anchors(completed_body, _ISSUE_BODY_WITH_PRD) == completed_body


def test_append_missing_contract_anchors_skips_issues_without_prd() -> None:
    """无 PRD 锚点的 Issue 正文不被改动。"""
    fallback_body = "Closes #7\n\nGenerated by issue-agent-runner.\n"
    assert append_missing_contract_anchors(fallback_body, _ISSUE_BODY_WITHOUT_PRD) == fallback_body


@pytest.mark.parametrize("linked_prd_path", (_PENDING_PRD_PATH, _ARCHIVED_PRD_PATH))
def test_append_missing_contract_anchors_only_adds_what_is_missing(linked_prd_path: str) -> None:
    """正文已引用 PRD（pending 或归档路径）时只补声明，不重复追加 PRD 行。"""
    body_with_prd_link = f"Closes #42\n\nSee {linked_prd_path} for context.\n"
    completed_body = append_missing_contract_anchors(body_with_prd_link, _ISSUE_BODY_WITH_PRD)
    assert completed_body.count(linked_prd_path) == 1
    assert "- PRD:" not in completed_body
    assert find_pr_body_contract_violations(completed_body, _ISSUE_BODY_WITH_PRD) == []


def test_annotation_block_roundtrip() -> None:
    """标注块写入的 marker 必须能被合并队列侧的解析函数原样读回。"""
    violations = ["prd-link", "merge-acceptance"]
    block = build_contract_annotation_block(violations)
    assert parse_contract_annotation(block) == violations
    assert has_contract_annotation(block) is True
    assert has_contract_annotation(_COMPLIANT_BODY) is False
    assert parse_contract_annotation(_COMPLIANT_BODY) == []


def test_annotation_block_lists_human_readable_descriptions() -> None:
    block = build_contract_annotation_block(["prd-link"])
    assert "`prd-link`" in block
    assert "pending PRD path" in block


@pytest.mark.parametrize(
    ("marker_line", "expected"),
    [
        ("<!-- iar:pr-contract version=1 missing=prd-link -->", ["prd-link"]),
        (
            "<!--iar:pr-contract version=1 missing=prd-link,merge-acceptance-->",
            ["prd-link", "merge-acceptance"],
        ),
        ("<!-- iar:pr-contract version=1 missing= -->", []),
    ],
)
def test_parse_contract_annotation_marker_variants(marker_line: str, expected: list[str]) -> None:
    assert parse_contract_annotation(marker_line) == expected


# ---------------------------------------------------------------------------
# 发布端集成：确定性正文由代码补锚点，agent 正文缺锚点走软门标注
# ---------------------------------------------------------------------------


def _publish_issue(number: int, body: str):
    from backend.core.shared.models.agent_runner import IssueSummary

    return IssueSummary(
        number=number,
        title="Test Feature",
        url=f"https://github.com/example/repo/issues/{number}",
        body=body,
        labels=(),
    )


def _fake_runner_for(branch: str):
    from backend.core.shared.models.agent_runner import CommandResult
    from tests.conftest import FakeProcessRunner
    from tests.support.agent_runner import git_remote_command, git_remote_result

    return FakeProcessRunner(
        responses={
            ("git", "branch", "--show-current"): CommandResult(
                command=("git", "branch", "--show-current"),
                return_code=0,
                stdout=f"{branch}\n",
                stderr="",
            ),
            ("git", "status", "--porcelain"): CommandResult(
                command=("git", "status", "--porcelain"),
                return_code=0,
                stdout="",
                stderr="",
            ),
            git_remote_command(): git_remote_result("origin"),
        }
    )


@pytest.fixture(autouse=True)
def _hide_host_prd_skill(monkeypatch: pytest.MonkeyPatch) -> None:
    """默认让发布契约参考文本不可达，避免 agent 模式测试读到宿主机上真实安装的 prd skill。"""
    from backend.core.use_cases import agent_runner_publish as publish_module

    monkeypatch.setattr(publish_module, "load_prd_publish_contract", lambda: None)


def _draft_pr_app_config(*, mode: str, **target_overrides: str):
    """构造只开启 ``draft_pr`` 生成的 AppConfig，``target_overrides`` 透传给 target 配置。"""
    from backend.core.shared.models.agent_runner import (
        AppConfig,
        GeneratedContentConfig,
        GeneratedContentTargetConfig,
    )

    return AppConfig(
        generated_content=GeneratedContentConfig(
            enabled=True,
            draft_pr=GeneratedContentTargetConfig(enabled=True, mode=mode, **target_overrides),
        )
    )


def _published_pr_call(issue, app_config, *, content_generator=None) -> dict:
    """走一遍 ``create_draft_pr``，返回 FakeGitHubClient 记录下的唯一一次建 PR 调用。"""
    from backend.core.use_cases.agent_runner_publish import create_draft_pr
    from tests.conftest import FakeGitHubClient

    fake_client = FakeGitHubClient()
    create_draft_pr(
        issue,
        Path("."),
        app_config,
        fake_client,
        _fake_runner_for(f"issue-{issue.number}"),
        content_generator=content_generator,
    )
    pr_calls = [c for c in fake_client.calls if c["method"] == "create_draft_pr"]
    assert len(pr_calls) == 1
    return pr_calls[0]


def test_create_draft_pr_fallback_body_gets_contract_anchors() -> None:
    """生成产出为空落到 fallback body 时，PRD 交付的锚点由代码补齐，不再被标注违规。"""
    from backend.core.shared.models.agent_runner import AppConfig

    issue = _publish_issue(42, _ISSUE_BODY_WITH_PRD)
    published_body = _published_pr_call(issue, AppConfig())["body"]
    assert published_body.startswith("Closes #42")
    assert f"- PRD: {_ARCHIVED_PRD_PATH}" in published_body
    assert MERGE_ACCEPTANCE_MARKER_TEXT in published_body
    assert find_pr_body_contract_violations(published_body, issue.body) == []
    assert has_contract_annotation(published_body) is False


def test_create_draft_pr_generation_disabled_body_gets_contract_anchors() -> None:
    """整体关闭内容生成时同样走 fallback body，锚点也要补齐。"""
    from backend.core.shared.models.agent_runner import AppConfig, GeneratedContentConfig

    issue = _publish_issue(42, _ISSUE_BODY_WITH_PRD)
    app_config = AppConfig(generated_content=GeneratedContentConfig(enabled=False))
    published_body = _published_pr_call(issue, app_config)["body"]
    assert find_pr_body_contract_violations(published_body, issue.body) == []
    assert has_contract_annotation(published_body) is False


def test_create_draft_pr_template_body_gets_contract_anchors() -> None:
    """template 模式渲染出的 ``body_template`` 同样是确定性正文，锚点由代码补齐。"""
    issue = _publish_issue(42, _ISSUE_BODY_WITH_PRD)
    app_config = _draft_pr_app_config(
        mode="template",
        title_template="[Agent] {issue_title}",
        body_template="Closes #{issue_number}\n\nGenerated by issue-agent-runner.",
    )
    pr_call = _published_pr_call(issue, app_config)
    assert pr_call["title"] == "[Agent] Test Feature"
    assert pr_call["body"].startswith("Closes #42\n\nGenerated by issue-agent-runner.")
    assert find_pr_body_contract_violations(pr_call["body"], issue.body) == []
    assert has_contract_annotation(pr_call["body"]) is False


def test_create_draft_pr_annotates_agent_body_that_ignores_teaching() -> None:
    """agent 撰写的正文缺锚点不被静默补齐：保留软门标注，暴露教学失效。"""
    from tests.conftest import FakeContentGenerator

    issue = _publish_issue(42, _ISSUE_BODY_WITH_PRD)
    app_config = _draft_pr_app_config(mode="agent", output="markdown", prompt="Generate a PR body.")
    generator = FakeContentGenerator(response="[Agent] Test Feature\n\nCloses #42\n\nDone.\n")
    published_body = _published_pr_call(issue, app_config, content_generator=generator)["body"]
    assert generator.prompts, "agent generator should have been invoked"
    assert parse_contract_annotation(published_body) == ["prd-link", "merge-acceptance"]
    assert "autopilot merge queue will refuse" in published_body
    assert "Human Acceptance And PRD Archive" not in published_body


def test_create_draft_pr_agent_closes_first_line_does_not_become_title() -> None:
    """agent 遵守 "首行 Closes #N" 约定时，该行不能被当成 PR 标题。"""
    from tests.conftest import FakeContentGenerator

    issue = _publish_issue(42, _ISSUE_BODY_WITH_PRD)
    app_config = _draft_pr_app_config(mode="agent", output="markdown", prompt="Generate a PR body.")
    generator = FakeContentGenerator(response="Closes #42\n\n## Summary\n\nDone.\n")
    pr_call = _published_pr_call(issue, app_config, content_generator=generator)
    assert pr_call["title"] == "[Agent] Test Feature"
    assert pr_call["body"].startswith("Closes #42")


def test_create_draft_pr_no_annotation_for_issues_without_prd() -> None:
    """无 PRD 锚点的 Issue 既不补锚点也不追加契约标注，正文保持 fallback 原样。"""
    from backend.core.shared.models.agent_runner import AppConfig

    issue = _publish_issue(7, _ISSUE_BODY_WITHOUT_PRD)
    published_body = _published_pr_call(issue, AppConfig())["body"]
    assert published_body == "Closes #7\n\nGenerated by issue-agent-runner.\n"
    assert has_contract_annotation(published_body) is False


def test_create_draft_pr_injects_contract_teaching_into_agent_prompt(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    """agent 模式下发布契约参考文本必须进入生成 prompt（教学注入）。"""
    from backend.core.shared.models.agent_runner import (
        AppConfig,
        CommandResult,
        GeneratedContentConfig,
        GeneratedContentTargetConfig,
    )
    from backend.core.use_cases import agent_runner_publish as publish_module
    from backend.core.use_cases.agent_runner_publish import create_draft_pr
    from tests.conftest import FakeGitHubClient

    skill_path = _write_skill(tmp_path, with_reference=True)
    contract_text = load_prd_publish_contract(skill_path)
    assert contract_text is not None
    monkeypatch.setattr(publish_module, "load_prd_publish_contract", lambda: contract_text)

    captured_prompts: list[str] = []

    class RecordingGenerator:
        def generate(
            self, agent_name: str, prompt: str, *, cwd, timeout=None, model_selection=None
        ):
            captured_prompts.append(prompt)
            return CommandResult(
                command=("fake",),
                return_code=0,
                stdout=(
                    "[Agent] Test Feature\n\nCloses #42\n\n"
                    "- PRD: tasks/pending/20260928-feature.md\n"
                    f"{MERGE_ACCEPTANCE_MARKER_TEXT}\n"
                ),
                stderr="",
            )

    app_config = AppConfig(
        generated_content=GeneratedContentConfig(
            enabled=True,
            draft_pr=GeneratedContentTargetConfig(
                enabled=True,
                mode="agent",
                output="markdown",
                prompt="Generate a draft PR body.",
            ),
        ),
    )
    issue = _publish_issue(42, _ISSUE_BODY_WITH_PRD)
    fake_client = FakeGitHubClient()
    create_draft_pr(
        issue,
        Path("."),
        app_config,
        fake_client,
        _fake_runner_for("issue-42"),
        content_generator=RecordingGenerator(),
    )
    assert captured_prompts, "agent generator should have been invoked"
    assert "PR-Native Acceptance contract" in captured_prompts[0]
    assert MERGE_ACCEPTANCE_MARKER_TEXT in captured_prompts[0]
    # 教学注入后原 config prompt 仍保留在 prompt 尾部。
    assert captured_prompts[0].endswith("Generate a draft PR body.")
    # 合规正文不应被追加标注块。
    pr_calls = [c for c in fake_client.calls if c["method"] == "create_draft_pr"]
    assert has_contract_annotation(pr_calls[0]["body"]) is False


# ---------------------------------------------------------------------------
# 合并端硬门集成：带标注 marker 的 PR 不自动合并
# ---------------------------------------------------------------------------


def test_merge_queue_skips_prs_with_contract_annotation(tmp_path) -> None:
    """发布端标注过 ``iar:pr-contract`` 的 PR 必须被合并队列拒绝。"""
    from backend.core.shared.models.agent_runner import PullRequestContext
    from backend.core.use_cases.agent_runner_merge_queue import _process_one
    from tests.conftest import FakeGitHubClient, FakeProcessRunner
    from tests.test_agent_runner_merge_queue import _make_config, _make_issue

    github = FakeGitHubClient()
    pr_context = PullRequestContext(
        pr_url="https://github.com/example/repo/pull/70",
        branch="issue-70",
        head_sha="abc1234",
        base_sha="base1234",
        mergeable=True,
        checks_state="SUCCESS",
        number=70,
        body="Closes #70\n\n" + build_contract_annotation_block(["prd-link"]),
    )
    github.set_pr_context("issue-70", pr_context)
    github._issue_comments[70] = ["PR Branch: `issue-70`"]

    outcome = _process_one(
        repo_path=tmp_path,
        config=_make_config(require_verifier_pass=False, auto_sign_off=False),
        issue=_make_issue(number=70, labels=("agent/review",)),
        github_client=github,
        process_runner=FakeProcessRunner(),
        supervisor_agent="auto",
    )
    assert outcome.action == "skipped_pr_contract_missing"
    merge_calls = [c for c in github.calls if c.get("method") == "merge_pull_request"]
    assert merge_calls == []
    # 硬门在 rebase / 签核之前生效，不产生 body 变更。
    body_calls = [c for c in github.calls if c.get("method") == "update_pull_request_body"]
    assert body_calls == []


def test_merge_queue_merges_prs_without_contract_annotation(tmp_path, monkeypatch) -> None:
    """无标注 marker 的 PR（含存量 PR）不受硬门影响。"""
    from backend.core.shared.models.agent_runner import (
        CommandResult,
        PullRequestContext,
    )
    from backend.core.use_cases.agent_runner_merge_queue import _process_one
    from tests.conftest import FakeGitHubClient, FakeProcessRunner
    from tests.test_agent_runner_merge_queue import _make_config, _make_issue

    # 复用 merge queue 测试模块的 worktree stub：_process_one 会解析 worktree。
    stub_worktree = tmp_path / "worktree"
    stub_worktree.mkdir()
    monkeypatch.setattr(
        "backend.core.use_cases.agent_runner_merge_queue.create_or_reuse_worktree",
        lambda *args, **kwargs: stub_worktree,
    )

    def fake_run_verification(*args, **kwargs):  # noqa: ARG001,ANN002,ANN003
        return [CommandResult(command=("git", "status"), return_code=0, stdout="", stderr="")]

    monkeypatch.setattr(
        "backend.core.use_cases.agent_runner_merge_queue.run_verification",
        fake_run_verification,
    )
    monkeypatch.setattr(
        "backend.core.use_cases.agent_runner_merge_queue.execute_rebase",
        lambda **kwargs: [],
    )
    monkeypatch.setattr(
        "backend.core.use_cases.agent_runner_merge_queue._diff_paths",
        lambda *args, **kwargs: (["src/main.py"], False),
    )

    github = FakeGitHubClient()
    pr_context = PullRequestContext(
        pr_url="https://github.com/example/repo/pull/71",
        branch="issue-71",
        head_sha="abc1234",
        base_sha="base1234",
        mergeable=True,
        checks_state="SUCCESS",
        number=71,
        body="Closes #71\n\nGenerated by issue-agent-runner.\n",
    )
    github.set_pr_context("issue-71", pr_context)
    github._issue_comments[71] = ["PR Branch: `issue-71`"]

    outcome = _process_one(
        repo_path=tmp_path,
        config=_make_config(require_verifier_pass=False, auto_sign_off=False),
        issue=_make_issue(number=71, labels=("agent/review",)),
        github_client=github,
        process_runner=FakeProcessRunner(),
        supervisor_agent="auto",
    )
    assert outcome.action == "merged"
